---
- name: Install Debian/Ubuntu-specific packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
  when: ansible_os_family == "Debian"
  tags: 
    - sudo
    - install_sudo
