---
- name: Install ufw (state=present is optional)
  apt:
    name: ufw
    state: present

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow

- name: Allow SSH in UFW
  ufw: 
    rule: allow 
    port: 22
    proto: tcp

- name: Allow addional ports in UFW
  ufw: 
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - "{{ ufw_additional_rules }}"
  when: ufw_additional_rules is defined