---
- name: Install Debian/Ubuntu-specific packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - tree
    - net-tools
    - vim
  when: ansible_os_family == "Debian"
  tags: mypkg

